"""add waitlisted

Revision ID: 55ab864e94d1
Revises: 0f701218a691
Create Date: 2023-02-20 22:08:01.109994+00:00

"""
import sqlalchemy as sa  # noqa
import sqlmodel  # noqa

from alembic import op

# revision identifiers, used by Alembic.
revision = "55ab864e94d1"
down_revision = "0f701218a691"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("githubusers", sa.Column("waitlisted", sa.Boolean(), nullable=True))
    # set all existing users to waitlisted
    op.execute(
        """
        UPDATE githubusers
        SET waitlisted = true
        """
    )
    # make sure the column is not nullable
    op.alter_column("githubusers", "waitlisted", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("githubusers", "waitlisted")
    # ### end Alembic commands ###
