"""init

Revision ID: 44f6e638eb9e
Revises:
Create Date: 2023-02-20 19:51:58.297399+00:00

"""
from alembic import op
import sqlalchemy as sa  # noqa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision = "44f6e638eb9e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "githubusers",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("emails", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_githubusers_id"), "githubusers", ["id"], unique=False)
    op.create_index(
        op.f("ix_githubusers_username"), "githubusers", ["username"], unique=True
    )
    op.create_table(
        "llms",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("modal_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("clone_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("githubuser_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["githubuser_id"],
            ["githubusers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clone_url"),
        sa.UniqueConstraint("modal_url"),
    )
    op.create_index(op.f("ix_llms_id"), "llms", ["id"], unique=False)
    op.create_index(op.f("ix_llms_phone_number"), "llms", ["phone_number"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llms_phone_number"), table_name="llms")
    op.drop_index(op.f("ix_llms_id"), table_name="llms")
    op.drop_table("llms")
    op.drop_index(op.f("ix_githubusers_username"), table_name="githubusers")
    op.drop_index(op.f("ix_githubusers_id"), table_name="githubusers")
    op.drop_table("githubusers")
    # ### end Alembic commands ###
