"""add llms

Revision ID: 838e67bebc6a
Revises: a1b4a9c75700
Create Date: 2023-02-18 20:45:06.992015+00:00

"""
from alembic import op
import sqlalchemy as sa  # noqa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision = "838e67bebc6a"
down_revision = "a1b4a9c75700"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llms",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("modal_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("clone_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clone_url"),
        sa.UniqueConstraint("modal_url"),
    )
    op.create_index(op.f("ix_llms_id"), "llms", ["id"], unique=False)
    op.create_index(op.f("ix_llms_phone_number"), "llms", ["phone_number"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llms_phone_number"), table_name="llms")
    op.drop_index(op.f("ix_llms_id"), table_name="llms")
    op.drop_table("llms")
    # ### end Alembic commands ###
