"""json type

Revision ID: 0f701218a691
Revises: 44f6e638eb9e
Create Date: 2023-02-20 19:55:58.899054+00:00

"""
from alembic import op
import sqlalchemy as sa  # noqa
import sqlmodel  # noqa


# revision identifiers, used by Alembic.
revision = "0f701218a691"
down_revision = "44f6e638eb9e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("githubusers", "emails", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("githubusers", "emails", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
